# Generated by Django 2.2.1 on 2019-05-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='type',
        ),
    ]
