# Generated by Django 2.2.1 on 2019-05-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190529_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='data/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
