# Generated by Django 2.2.1 on 2019-05-29 20:23

import application.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190529_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='CSV',
            field=models.FileField(upload_to='data/', validators=[application.validators.validate_file_extension]),
        ),
    ]
